# permissions for end users to edit urlshortenerapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: urlshortenerapp-editor-role
rules:
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - urlshortenerapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - urlshortenerapps/status
  verbs:
  - get
