# permissions for end users to view urlshortenerapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: urlshortenerapp-viewer-role
rules:
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - urlshortenerapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - urlshortenerapps/status
  verbs:
  - get
